#201 피드의 글을 불러올 때마다 튜토리얼 화면이 나오는 버그 수정하기
woowacourse-teams/2020-saebyeok pull request #202
Opened 2020-09-18 14:52 UTC by icyMojito

resolves: #201 

Feed 화면을 불러올 시 created()에서 localStorage에 담긴 check 값을 검사하여 
Tutorial 화면 띄우기 값(tutorialDialog)을 true 혹은 false로 바꾸는데요,
하단에 새로 피드를 불러올 경우에는 created()를 타지 않다 보니 계속 Tutorial 화면이 뜨는 것으로 추측되네요..!
그래서 Tutorial 화면의 '시작해볼게요' 버튼 클릭 이벤트에 emit을 넣고
Feed에서 emit을 받아 Tutorial 화면 띄우기 값(:dialog)을 false로 바꾸는 방식을 적용했습니다!!

제가 몇 번 확인했을 때는 문제없이 되었는데, 여러분들께서도 확인 한 번씩만 부탁드립니다 🙇🏻‍♀️

2020-09-21 12:34 UTC, hwanghe159 approved these changes
이제 한번뜨고 안뜨네요!! 수고많았습니다 ㅎㅎㅎ

2020-09-21 14:59 UTC, include42 approved these changes
당황스러웠을텐데 깔끔하게 고쳐주시고, 참 고생이 많았어요 쿨라임!!
작동에 큰 문제는 없어보이네요

바로 approve!

2020-09-22 08:19 UTC, SujinEmilyCho approved these changes
문제 없이 잘 동작하네요!
놀랐을 텐데, 빠른 대응 감사합니다 🙏

2020-09-22 08:20 UTC, hotheadfactory requested changes
역시 꼼꼼한 쿨라임!! 버그 픽스 확인했습니다!!

2020-09-22 08:21 UTC, hotheadfactory requested changes
헛 잘못 눌렀다! Approve 드릴게요!

2020-09-22 08:21 UTC, hotheadfactory approved these changes
두번이나 손이 미끄러졌습니다 ㅠㅜ

2020-09-22 08:33 UTC, merged